_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
            "3":
                - 16
                - 23
                - 55
            "4": 3.8.10
            "5": 0.19.7
            "6": 4.46.2
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
classifier:
    value:
        hidden_dims:
            - 512
        test: true
        test_weights_path: /results/simple_MLP/timesformer2/best_epoch.pt
        train: true
        train_weights_path: null
data:
    value:
        annotations_path: /workspace/tfg_hhernandez/annotations
        batch_size: 32
        data_path: /dataset/
        down_sampling_rate: 5
        test:
            - P_07
            - P_08
            - P_11
            - P_15
        train:
            - P_03
            - P_04
            - P_05
            - P_06
            - P_09
            - P_10
            - P_12
            - P_13
            - P_14
            - P_18
            - P_19
            - P_20
        val:
            - P_01
            - P_02
            - P_16
            - P_17
        workers: 1
model:
    value:
        fusion_strategy: concat
        multimodal: false
object_detector:
    value:
        max_detected_objects: 4
        object_model: GT
        object_recopilation_strategy: lastframe
save_dir:
    value: /results/simple_MLP/timesformer2
seed:
    value: 0
train_params:
    value:
        dropout: 0.2
        epochs: 20
        lr: 0.0005
        save_every: 20
        weight_decay: 0.3
video_model:
    value:
        block_size: 16
        extract_features: true
        name: timesformer
