_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.10
            "5": 0.19.6
            "6": 4.46.2
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
classifier:
    value:
        hidden_dims:
            - 512
        test: true
        test_weights_path: /results/simple_MLP/videomae/best_epoch.pt
        train: true
        train_weights_path: None
data:
    value:
        annotations_path: /workspace/tfg_hhernandez/annotations
        batch_size: 64
        data_path: /dataset/
        down_sampling_rate: 5
        test:
            - P_07
            - P_08
            - P_11
            - P_15
        train:
            - P_03
            - P_04
            - P_05
            - P_06
            - P_09
            - P_10
            - P_12
            - P_13
            - P_14
            - P_18
            - P_19
            - P_20
        val:
            - P_01
            - P_02
            - P_16
            - P_17
        workers: 4
model:
    value:
        fusion_strategy: concat
        get_object_features: false
        get_text_features: false
        multimodal: false
object_detector:
    value:
        embedding_size: 768
        extract_features: false
        max_detected_objects: 4
        object_encoder: vit
        object_model: GDino
        object_recopilation_strategy: 1stframe
save_dir:
    value: /results/simple_MLP/videomae
seed:
    value: 0
text_encoder:
    value:
        embedding_size: 768
        extract_features: false
        text_model: Roberta
train_params:
    value:
        dropout: 0.1
        epochs: 20
        lr: 0.0005
        optimizer: adamw
        save_every: 20
        weight_decay: 0.1
video_model:
    value:
        block_size: 16
        extract_features: false
        name: timesformer
